apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: products-msv
  name: products-msv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-msv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: products-msv
    spec:
      containers:
        - image: southamerica-west1-docker.pkg.dev/microservices-424800/image-registry/products-msv
          name: products-msv
          env:
            - name: PORT
              value: "3001"
            - name: NATS_SERVERS
              value: "nats://nats"
            - name: DB_LOGGING
              value: "query,error"
            - name: DB_LOGGING_ENABLED
              value: "false"
            - name: DB_URL
              value: "postgresql://productsdb_owner:8TCM6weoWbKy@ep-billowing-mode-a5rj0t9l.us-east-2.aws.neon.tech/productsdb?sslmode=require"

          resources: {}
status: {}
