apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-msv
  name: payments-msv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-msv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-msv
    spec:
      containers:
        - image: southamerica-west1-docker.pkg.dev/microservices-424800/image-registry/payments-msv
          name: payments-msv
          env:
            - name: PORT
              value: "3003"
            - name: STRIPE_SUCCESS_URL
              value: "http://localhost:3003/payments/success"
            - name: STRIPE_CANCEL_URL
              value: "http://localhost:3003/payments/cancelled"
            - name: NATS_SERVERS
              value: "nats://nats"
            - name: STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: stripe_secret
            - name: STRIPE_ENDPOINT_SECRET
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: stripe_endpoint-secret
          resources: {}
status: {}
