apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: auth-msv
  name: auth-msv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-msv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth-msv
    spec:
      containers:
      - image: southamerica-west1-docker.pkg.dev/microservices-424800/image-registry/auth-msv
        name: auth-msv
        env:
          - name: NATS_SERVERS
            value: "nats://nats"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: database_url
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: jwt_secret
          - name: PORT
            value: "3000"
        resources: {}
status: {}
